name: nodejs-dev-env
services:
  node-dev-container:
    image: node-dev-container
    build:
      context: .
      dockerfile: Dockerfile
    cpus: 2
    mem_limit: 4g
    tty: true
    volumes:
      - nodejs-dev-env:/app:rw
    networks:
      - nodejs-dev-env

volumes:
  nodejs-dev-env:

networks:
  nodejs-dev-env:
